- 출처 : https://rfriend.tistory.com/349?category=675917   
https://rfriend.tistory.com/352?category=675917

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


### 배열 조작

#### 1. cbind
- np.r_[배열1, 배열2]
- np.hstack([배열1, 배열2])    (V)
- np.concatenate((배열1, 배열2), axis =0)

#### 2. rbind
- np.r_[[배열1], [배열2]]
- np.vstack([배열1, 배열2])     (V)
- np.concatenate((배열1, 배열2), axis = 1)

In [9]:
## 1. cbind
print(np.r_[a,b])
print(np.hstack([a,b]))
print(np.concatenate((a,b), axis = 0))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
# 2. rbind
print(np.r_[[a],[b]])
print(np.vstack([a,b]))
print(np.concatenate((a,b), axis=1))  # error : 2D 이상 배열에서만 가능

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


AxisError: axis 1 is out of bounds for array of dimension 1

In [13]:
# +) 컬럼별로 행만들기
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

---
### 다차원 배열 -> 1차원배열로 조작
- 1) np.ravel(배열, order = 'C')  # order : C,F,K / default = C

In [16]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 1. np.ravel()

In [17]:
np.ravel(x, order = 'C')  # 각 행 flattening

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.ravel(x, order = 'F')  # 각 열 flattening

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [20]:
np.ravel(x, order = 'K') # 메모리에서 발생하는 순서대로 인덱싱하여 flattening

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])